In [7]:
print(19 % 4 != 300 / 10 / 10 and False)
print(-(1 ** 2 ) < 2 ** 0 and 10 % 10 <= 20 - 10 * 2)
print(2 ** 3 == 108 % 100 or ' Cleese ' == ' King Arthur ')

False
True
True


In [10]:
i = int = 0
user = input("Введите фразу:")
print(user[len(user)-1], end="")
while (i != len(user)-2):    
    i+=1
    print(user[i], end="")
print(user[0],end="")

Введите фразу:zxc
cxz

In [5]:
a = input()
a = int(a)
def fac(n):
    if n == 0:
        return 1
    return fac(n-1) * n
print(fac(a))

3
6


In [6]:
import random
a = input()
choice_list = ['rock', 'paper', 'scissors']
b = random.choice(choice_list)
if (a == 'rock') and (b == 'paper'):
    print('you lose')
else:
    if (a == 'paper') and (b == 'rock'):
        print('you win')
    else:
        if (a == 'paper') and (b == 'scissors'):
            print('you lose')
        else:
            if (a == 'scissors') and (b == 'paper'):
                print('you win')
            else:
                if (a == 'scissors') and (b == 'rock'):
                    print('you lose')
                else:
                    if (a == 'rock') and (b == 'scissors'):
                        print('you win')
                    else:
                        if a == b:
                            print('draw')
print('you = ',a,' random = ',b)

scissors
you lose
you =  scissors  random =  rock


In [8]:
from random import randint
b = int(input()) # Массивы
a = int(input()) # Элементы
Bigmas = [[i for i in range(a)]]
for i in range (b-1):
    Bigmas += [[i for i in range(a)]]
for T in range (b):
    for Y in range(a):
        Bigmas[T][Y] = randint(0,100)   
print(Bigmas)

1
2
[[87, 8]]


In [9]:
import numpy as np
import random 
m=[1,-1] 
summ=0
l=0
n=int(input())
a=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        a[i,j]=random.choice(m)
print(a)
for i in range(n):
    for j in range(n):
        summ+=a[i,j]*a[i,j-1]
        l+=a[i-1,j]*a[i,j]        
print(summ+l)

5
[[ 1. -1.  1. -1.  1.]
 [-1.  1. -1. -1.  1.]
 [ 1.  1.  1. -1.  1.]
 [-1.  1.  1. -1. -1.]
 [ 1.  1.  1.  1.  1.]]
2.0
